---
apiVersion: v1
kind: ReplicationController
metadata:
  name: backup-shell
  namespace: workbench
  labels:
    app: backup-shell
spec:
  template:
    metadata:
      name: backup-shell
      namespace: workbench
      labels:
        name: backup-shell
    spec:
      hostNetwork: true
      containers:
        - image: ndslabs/cluster-backup:latest
          imagePullPolicy: Always
          name: backup
          stdin: true
          tty: true
          command: [ "/bin/bash" ]
          env:
           - name: ETCD_HOST
             value: $(WORKBENCH_ETCD_SERVICE_HOST)
           - name: ETCD_PORT
             value: $(WORKBENCH_ETCD_SERVICE_PORT)
