apiVersion: v1
kind: Service
metadata:
  labels:
    component: workbench
  name: workbench-etcd
  namespace: workbench
spec:
  ports:
  - name: etcd
    port: 4001
    protocol: TCP
  selector:
    component: workbench
